# coding=utf-8
# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_library(
  name = 'hashing',
  sources = ['hashing.py', '__init__.py'],
)

python_library(
  name = 'tar',
  sources = ['tar.py', '__init__.py'],
)
