# coding=utf-8
# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_tests(
  sources = globs('*.py'),
  dependencies = [
    'contrib/docker/src/python/pants/contrib/docker/util:tar',
    'contrib/docker/src/python/pants/contrib/docker/util:hashing',

  ],
)
