# coding=utf-8

python_library(
  name = 'docker_image',
  sources = ['docker_image.py', '__init__.py'],
)

python_library(
  name = 'docker_layer',
  sources = ['docker_layer.py', '__init__.py'],
)

python_library(
  name = 'docker_remote_image',
  sources = ['docker_remote_image.py', '__init__.py'],
)

python_library(
  name = 'docker_dockerfile',
  sources = ['docker_dockerfile.py', '__init__.py'],
)
